### PR TITLE
dungeon dive itempool adjustment

### PR DESCRIPTION
**Pull request by EpochFlame**
swap the useless shovel/shroom with two hearts. the shovel does admittedly allow for rupee and heart farming in the safe areas, but so does cutting grass.
this would make a full heartbar on otherwise normal settings.

personally i would like one of the twenty rupee chests to be swapped out with a medicine, but that's just my opinion, and not having medicine makes for an interesting challenge. having one (1) medicine available would be neat though

### CODE REVIEW

**Comment by EpochFlame** [comment]
this was inspired by playing dungeon dive for the first time earlier today and fruitlessly searching for a hidden dig spot to the witch house

**Comment by daid** [comment]
Pretty sure this will bug out if you have heart containers not shuffled, as then it won't have places to put the extra heart containers (which then need to be in boss rooms). I'm not against removing the shovel and toadstool.

**Comment by EpochFlame** [comment]
> Pretty sure this will bug out if you have heart containers not shuffled, as then it won't have places to put the extra heart containers (which then need to be in boss rooms). I'm not against removing the shovel and toadstool.

Tested today- works fine, found one heart container in the shop for 200 rupees, haven't found the other yet. I did notice with dungeon dive settings, the spoiler log won't generate, but that happens on current latest as well, and isn't related to the PR.

**Comment by EpochFlame** [comment]
Seed was C0B9A0DFFC01C92252AB49FFD7CF0DE8 with default settings, aside from Heart Container randomization turned off and Dungeon Dive. One of the randomized Heart Containers will generate as the 200-rupee shop item.

**Pull request merged**
