### PR TITLE
Location names

### PR DESCRIPTION
**Pull request by kbranch**
This mostly just adds names to Locations, although I did also separate bosses and minibosses from their rooms to make it easier to see whether a boss can be checked when shuffled.

In general I only added names to locations that don't directly contain checks. The Archipelago port already had a few overworld names, so I used those where they exist. I can add more names if you'd prefer.

I both ran this through my brute force logic tester script and made a few hundred seeds with a few different settings, to make sure I didn't break something weird with so much code getting touched.

### CODE REVIEW

**Comment by daid** [comment]
I like!

I was also thinking, maybe we can optionally add some X/Y coordinates to the locations. So you could plot the logic on top of the maps as a graph. But, might not be usable or too much manual work to setup.

**Comment by kbranch** [comment]
Oh, yeah, just points with lines between them would be a good intermediate before the full polygons I was picturing (and still useful on top of the polygons). I stopped short of any kind of coordinates/shapes for now because of the manual work, but I do plan on going back through it.

Are coordinates something you'd like in LADXR itself? My usual approach is to use LADXR's IDs as keys for piles of JSON, but putting them in the logic definition works just as well here for me.

**Comment by daid** [comment]
Mmmm... good point, I don't think I need to positions in LADXR, and a different json file would make it easier to have some visual tool for positioning these nodes.

**Comment by kbranch** [comment]
Got it - I'll go the JSON route when I revisit this. I do have a very unpolished tool for picking coordinates by tile rather than raw image coordinates, so the data should be usable outside of Magpie.

**Pull request merged**
