### PR TITLE
Added friendlier spoiler log locations

### PR DESCRIPTION
**Pull request by kbranch**
I added a checkMetadata class for the names and general locations of checks.  I'm picturing the 'area' member being used in the future for somewhat vague hints like ZOoTR does.  I just made some arbitrary decisions about how to group checks into areas, I'm not attached to any of them.

I also added a nameId property to itemInfo and all classes derived from it that returns a key for use in the checkMetadataTable that contains all the check names in the game.

Python isn't my primary language, I'm open to any suggestions.

### CODE REVIEW

**Comment by kbranch** [comment]
Sure, I can make the changes - what did you have in mind?  Sorry if I missed it somewhere, I haven't used GitHub for pull requests.

**Comment by daid** [comment]
Looks like github ate my other comment...

Came down to adding the room number as parameter to the ItemInfo init function, so all items have a room. And turning metadata into a property so it setting it is not needed in all the different classes.

**Comment by kbranch** [comment]
Got it, good call.  Not sure why I didn't do that in the first place.  I think I saw moving your code as more likely to break things than tacking my own stuff on top - still getting used to open source contributions, haha.

Thanks, I'll make those changes in a few minutes.

**Comment by kbranch** [comment]
I noticed a few dumb things that I left behind before as I was making these changes, like leaving the room number purely in the nameId property in one case.  Feel free to point out anything like that that you notice.

**Pull request merged**
