### PR TITLE
Allowed loading a ROM without file IO

### PR DESCRIPTION
**Pull request by kbranch**
This makes the ROM constructor accept either a filename or the ROM bytes. Magpie's autotracker never knows were the ROM file is, it has it in memory.

### CODE REVIEW

**Comment by daid** [comment]
Alternatively you could use an IO.StringIO object?

**Comment by kbranch** [comment]
I looked into an approach along those lines originally, but the fact that ROM accepts a path that it passes directly to open() stumped me. Maybe I'm misunderstanding, though?

Or are you suggesting ROM accept a stream rather than bytes?

**Comment by daid** [comment]
Yeah, make the class accept a filestream instead of a filename.

**Comment by kbranch** [comment]
Got it, how's this look?

Also, merry Christmas!

**Pull request merged**
