### PR TITLE
docs: overhaul for v0.10

### PR DESCRIPTION
**Pull request by foxsouns**
This updates the docs, mainly to just match current rando logic, and some typoes I spotted on the way. It also fixes icons, adds `<!DOCTYPE html>` to the top, and removes the dependency upon CloudFlare for css (by embedding it).

### CODE REVIEW

**Comment by foxsouns** [comment]
actually, i think there's some other places that should get some touch-ups as well, mainly just. throwing the sha-1 for the actual rom, i guess.

**Comment by foxsouns** [comment]
okay, screw it! i'm going to completely reword the readme/docs: they aren't perfect grammar, and i feel like i could do better at it, and bring it all up to date.

**Comment by foxsouns** [comment]
alright, i think i'm ready for you to look at this. above the hood is a bunch of little changes, a few big ones involved with bringing it up to date, and the only change under-the-hood here is the localizing of css: nothing visibly different with the site, but now it doesn't ping cloudflare every time you load it. also fixes the ico not being loaded for the subsites.

**Comment by daid** [comment]
Looks good. I'm thinking about giving the whole site some design update at some point. As it's quite bare bones and minimal, and could use some visual "flare"

**Pull request merged**
