### PR TITLE
Added a plan file option to the web UI

### PR DESCRIPTION
**Pull request by kbranch**
I've been working on using Magpie to export a plan file, so this adds a way to load a plan file to the web UI. I'm definitely open to suggestions on how to do this better.

What I have so far is live at https://dev.magpietracker.us/ if you're curious - right click a check, click the little right arrow, select an item to go there. Once you've placed the items you want to, go to the Plandomizer tab in the lower right underneath the item tracker and click Export as Plan. It's pretty basic, but it's a start.

### CODE REVIEW

**Comment by kbranch** [comment]
I fleshed this out a bit - just let me know if it's lacking anything you'd like to see.

**Comment by kabarakh** [comment]
any chance for this being merged? I got something I want to try out, and plando would really help me for that

**Comment by foxsouns** [comment]
+1, but only because i like it in general.

**Comment by daid** [comment]
other projects have been keeping me busy. Just took a look at it. The concept is fine, but I don't think it should be as prominent on the "main" page, as it's quite a "special" feature.

**Comment by kbranch** [comment]
Would you want a totally separate page, or just to make it less prominent? It could go in a collapsable container, maybe?

**Comment by daid** [comment]
Not sure, I'm open for suggestions.

**Comment by kbranch** [comment]
I could see it being on the main page but something small you can expand, maybe a little nondescript icon?

Another option might be a separate page that accepts a short string and a plan file, similar to the multiworld generator.

**Comment by daid** [comment]
I think a 2nd page would be best, it's quite a complicated feature to use unless someone else gives you a file. And at that point they can also point you to that page.

**Comment by kbranch** [comment]
Sounds good, I'll rework it.

**Comment by kbranch** [comment]
Okay, that should do it.

**Pull request merged**
